version: '3.1'
services:

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    volumes:
      - ./testutils/docker/postgres:/docker-entrypoint-initdb.d:ro

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/auth/health"]
    environment:
      - SERVER_PORT=9090
      - SPRING_PROFILES_ACTIVE=dev,delius,local-postgres,nomis
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth-db
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8081
      - DELIUS_ENABLED=true
      - DELIUS_ENDPOINT_URL=http://wiremock:8080/delius
      - DELIUS_ENDPOINT_TIMEOUT=1s
      - DELIUS_CLIENT_CLIENT-ID=delius-auth-api-client
      - DELIUS_CLIENT_CLIENT-SECRET=delius-auth-api-client

  auth-db:
    image: postgres:15
    networks:
      - hmpps
    container_name: auth-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth-db
    healthcheck:
      test: pg_isready -d auth-db

  find-and-refer-interventions-service:
    image: quay.io/hmpps/hmpps-find-and-refer-an-intervention-service
    restart: always
    networks:
      - hmpps
    container_name: find-and-refer-interventions-service
    depends_on:
      - postgres
    ports:
      - '8092:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - POSTGRES_URI=postgres:5432

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    container_name: nomis-user-roles-api
    networks:
      - hmpps
    depends_on:
      - hmpps-auth
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/health/ping" ]
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:9090/auth
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration,classpath:db/dev,filesystem:/seed

  wiremock:
    image: wiremock/wiremock
    networks:
      - hmpps
    restart: always
    ports:
      - "9092:8080"
    volumes:
      - ./wiremock_mappings:/home/wiremock/mappings
    command: '--verbose'

networks:
  hmpps:
