version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@10
  slack: circleci/slack@4.12.5
  node: circleci/node@4.5.2

parameters:
  releases-slack-channel:
    type: string
    default: interventions-dev-notifications
  node-version:
    type: string
    default: 20.17-browsers

jobs:
  build:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci --no-audit
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          command: |
            npm run build
      - run: # Run linter after build because the integration test code depend on compiled typescript...
          name: Linter check
          command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build
            - dist
            - assets

  unit_test:
    executor:
      name: hmpps/node
      tag: << pipeline.parameters.node-version >>
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: unit tests
          command: npm run test:ci
      - store_test_results:
          path: test_results/unit/xml
      - store_artifacts:
          path: test_results/unit
      - store_artifacts:
          path: test_results/unit/xml

  end_to_end_test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.49.1-noble
    circleci_ip_ranges: true # opt-in to jobs running on a restricted set of IPs
    steps:
      - run:
          name: Clone E2E repo
          command: |
            git clone https://github.com/ministryofjustice/hmpps-find-and-refer-an-intervention-e2e.git .
      - run:
          name: Update npm
          command: 'npm install -g npm@latest'
      - node/install-packages
      - run:
          name: Install Playwright
          command: npx playwright install
      - run:
          name: E2E Check
          command: |
            npx playwright test
      - store_artifacts:
          path: playwright-report

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - unit_test:
          requires:
            - build
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_docker:
          name: build_docker
          # filters:
          #   branches:
          #     only:
          #       - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: 'dev'
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context: hmpps-common-vars
          # filters:
          #   branches:
          #     only:
          #       - main
          requires:
            - helm_lint
            - unit_test
            - build_docker
          helm_timeout: 5m
      - end_to_end_test:
          context: hmpps-common-vars
          # filters:
          #   branches:
          #     only:
          #       - main
          # requires:
          #   - deploy_dev
      - hmpps/deploy_env:
          name: deploy_preprod
          env: 'preprod'
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - hmpps-find-and-refer-an-intervention-preprod-deploy
          requires:
            - deploy_dev
          helm_timeout: 5m
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: 'prod'
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-find-and-refer-an-intervention-prod-deploy
          requires:
            - request-prod-approval
          helm_timeout: 5m
