---
# Per environment values which override defaults in hmpps-find-and-refer-an-intervention-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: find-and-refer-intervention-dev.hmpps.service.justice.gov.uk
  
  allowlist:
    groups:
      - internal
      - circleci

  env:
    INGRESS_URL: "https://find-and-refer-intervention-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    FIND_AND_REFER_URL: "https://find-and-refer-intervention-api-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    REFER_AND_MONITOR_URL: "https://hmpps-interventions-ui-dev.apps.live-1.cloud-platform.service.justice.gov.uk"
    ACCREDITED_PROGRAMMES_URL: "https://accredited-programmes-manage-and-deliver-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "true"
    SENTRY_ENVIRONMENT: DEV


generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
