---
# Per environment values which override defaults in hmpps-find-and-refer-an-intervention-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: find-and-refer-intervention-preprod.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://find-and-refer-intervention-preprod.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    FIND_AND_REFER_URL: "https://find-and-refer-intervention-api-preprod.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    REFER_AND_MONITOR_URL: "https://hmpps-interventions-ui-preprod.apps.live-1.cloud-platform.service.justice.gov.uk"
    ACCREDITED_PROGRAMMES_URL: "https://accredited-programmes-manage-and-deliver-preprod.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: PRE-PRODUCTION
    AUDIT_ENABLED: "false"
    SENTRY_ENVIRONMENT: PRE-PRODUCTION

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
