name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "36 3 * * MON-FRI" # Every weekday
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@v0.7 # WORKFLOW_VERSION
    with:
      channel_id: interventions-dev-notifications
    secrets: inherit
